# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Install libpcap-dev
      run: |
          sudo apt-get update
          sudo apt-get install libpcap-dev

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./main.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0  # Replace with your desired tag
        release_name: Release 1.0.0
        draft: false
        prerelease: false

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release-artifacts
        path: ./main
   # - name: Test
     # run: go test -v ./shark
